apiVersion: v1
kind: Service
metadata:
  name: myflaskapp
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
  selector:
    app: myflaskapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp
spec:
  selector:
    matchLabels:
      app: myflaskapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myflaskapp
        image: myflaskapp
        ports:
        - containerPort: 5000

